# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/models/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/home/jmd/Workspace/school/uni/KPU/Terms/Summer 2025/INFO 2312/project/djr-backend/migrations"
